repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: tox-lint
        name: tox lint
        entry: tox -e lint
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
